apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fastapi
  name: fastapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fastapi
    spec:
      containers:
      - image: pippa99/fastapi:latest
        imagePullPolicy: Always
        name: fastapi
        ports:
        - containerPort: 8000
        resources: 
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
status: {}
